name: Greet people workflow
run-name: Greeting everyone from the list

on:
  workflow_dispatch: {}

jobs:
  greet_everyone:
    runs-on: ubuntu-latest
    #Herw we define our iteration
    strategy:
      matrix:
        people:
          - Piotr
          - Seba
          - Damian
          - Andrzej
    steps:
      - name: Call custom action
        id: custom_action
        uses: Jacek-cie/hello-world-action@v2
        with:
          name: ${{ matrix.people }}
          
      - name: Display length of the name
        run: |
          echo "The length of the name is: ${{ steps.custom_action.outputs.name_length }}"
      
